import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import type { ExternalPluginMetaEntry } from '../../../src/plugins/plugin-descriptor';
import { classifyCompat, isCompatible } from './host-version';
import { hasEnLocale, normalizeLocalesDir } from './locale-check';
import { readLockfile } from './lockfile';
import { GENERATED_MANIFEST_PATH, pluginDir } from './paths';
import { readManifest, validateManifest } from './plugin-meta';
import type { LockEntry, SignalRangePluginManifest } from './types';

/**
 * Header of the generated file. Kept as a line array so the backticks in the
 * prose need no escaping; must stay byte-identical to the committed empty form.
 */
const HEADER = [
  '/**',
  ' * AUTO-GENERATED by `pnpm run plugin -- sync`. DO NOT EDIT BY HAND.',
  ' *',
  ' * Regenerated from external-plugins.json + the signal-range-plugin.json of each',
  ' * clone under src/plugins-external/. Committed so a fresh checkout typechecks',
  ' * and builds without running any tool; empty upstream when no external plugins',
  ' * are installed.',
  ' *',
  ' * - `externalPluginManifest` is spread onto the end of `pluginManifest`, giving',
  ' *   each external plugin its own async chunk exactly like a built-in.',
  ' * - `externalPluginMeta` is read by the dev menu so it can list installed',
  ' *   external plugins (version, repo, compat) without fetching anything at',
  ' *   runtime. `compatible` is precomputed at sync time against the host',
  ' *   package.json version.',
  ' */',
  "import type { ExternalPluginMetaEntry, PluginDescriptor } from './plugin-descriptor';",
  '',
].join('\n');

const EMPTY_BODY = ['export const externalPluginManifest: PluginDescriptor[] = [];', '', 'export const externalPluginMeta: Record<string, ExternalPluginMetaEntry> = {};', ''].join(
  '\n'
);

export interface SyncReport {
  /** Plugin names present on disk and included in the generated manifest. */
  readonly included: string[];
  /** Plugin names in the lockfile whose clone is missing (dropped from the manifest). */
  readonly missing: string[];
  /** Plugin names present on disk but skipped because their manifest is invalid. */
  readonly invalid: { readonly name: string; readonly reason: string }[];
  /** Ids whose engine range does not satisfy the host version. */
  readonly incompatible: { readonly id: string; readonly engine: string }[];
}

// ── JS literal emitter ──────────────────────────────────────────────────────
// The generated file lives under src/ and is linted by Biome (single quotes,
// unquoted keys, trailing commas), so values are emitted in the exact form the
// formatter would produce rather than as raw JSON.

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/u;

// Values come from third-party plugin manifests. JSON.stringify leaves these
// unescaped; none belongs in an id or path, so escaping them changes nothing
// for a real plugin and keeps a hostile one from shaping the emitted source.
const UNSAFE_CHARS: Record<string, string> = {
  '<': '\\u003C',
  '>': '\\u003E',
  '\u2028': '\\u2028',
  '\u2029': '\\u2029',
};

/** Quote a string the way Biome's formatter would (single unless that needs more escapes). */
function quote(value: string): string {
  const json = JSON.stringify(value).replace(/[<>\u2028\u2029]/gu, (c) => UNSAFE_CHARS[c]);
  const singles = value.split("'").length - 1;
  const doubles = value.split('"').length - 1;

  if (singles > doubles) {
    return json;
  }

  return `'${json.slice(1, -1).replaceAll('\\"', '"').replaceAll("'", "\\'")}'`;
}

function key(name: string): string {
  return IDENTIFIER.test(name) ? name : quote(name);
}

/** Inline (single-line) literal for a JSON-compatible value. */
function inline(value: unknown): string {
  if (typeof value === 'string') {
    return quote(value);
  }
  if (typeof value === 'number' || typeof value === 'boolean') {
    return String(value);
  }
  if (value === null || value === undefined) {
    return 'null';
  }
  if (Array.isArray(value)) {
    return `[${value.map(inline).join(', ')}]`;
  }

  const entries = Object.entries(value as Record<string, unknown>).map(([k, v]) => `${key(k)}: ${inline(v)}`);

  return entries.length === 0 ? '{}' : `{ ${entries.join(', ')} }`;
}

/** Multi-line object literal, one property per line at `indent` spaces. */
function expanded(value: Record<string, unknown>, indent: number): string {
  const pad = ' '.repeat(indent);
  const lines = Object.entries(value).map(([k, v]) => `${pad}  ${key(k)}: ${inline(v)},`);

  return lines.length === 0 ? '{}' : `{\n${lines.join('\n')}\n${pad}}`;
}

/** Strip a TS/JS extension from a repo-relative entry path and normalize to POSIX. */
function toImportSpecifier(name: string, entry: string): string {
  const posix = entry.replaceAll('\\', '/').replace(/^\.\//u, '');
  const noExt = posix.replace(/\.(?:[cm]?[jt]sx?)$/u, '');

  return `@plugins-external/${name}/${noExt}`;
}

/**
 * Build the generated-manifest source text from the lockfile + on-disk clones.
 * Only plugins actually present on disk are included, so the file never contains
 * an import rspack cannot resolve.
 */
export function generateManifestSource(): { source: string; report: SyncReport } {
  const lock = readLockfile();
  const names = Object.keys(lock.plugins).sort((a, b) => a.localeCompare(b));
  const report: SyncReport = { included: [], missing: [], invalid: [], incompatible: [] };
  const descriptorBlocks: string[] = [];
  const metaBlocks: string[] = [];

  for (const name of names) {
    const dir = pluginDir(name);

    if (!existsSync(dir)) {
      report.missing.push(name);
      continue;
    }

    // Lenient here (prebuild path): a malformed third-party manifest is skipped
    // with a report entry rather than bricking the build. `add`/`update` are the
    // strict gates that block on validation errors.
    try {
      const manifest = readManifest(dir);
      const { errors } = validateManifest(manifest, { dir, expectedName: name });

      if (errors.length > 0) {
        report.invalid.push({ name, reason: errors[0] });
        continue;
      }

      emitPlugin(name, dir, manifest, lock.plugins[name], descriptorBlocks, metaBlocks, report);
    } catch (e) {
      report.invalid.push({ name, reason: (e as Error).message });
    }
  }

  if (descriptorBlocks.length === 0) {
    return { source: `${HEADER}\n${EMPTY_BODY}`, report };
  }

  const body = [
    'export const externalPluginManifest: PluginDescriptor[] = [',
    ...descriptorBlocks,
    '];',
    '',
    'export const externalPluginMeta: Record<string, ExternalPluginMetaEntry> = {',
    ...metaBlocks,
    '};',
    '',
  ].join('\n');

  return { source: `${HEADER}\n${body}`, report };
}

function emitPlugin(
  name: string,
  dir: string,
  manifest: SignalRangePluginManifest,
  lockEntry: LockEntry,
  descriptorBlocks: string[],
  metaBlocks: string[],
  report: SyncReport
): void {
  report.included.push(name);

  const localesDir = normalizeLocalesDir(manifest.localesDir);
  const hasLocales = hasEnLocale(dir, manifest.localesDir);
  const meta: ExternalPluginMetaEntry = {
    packageName: manifest.name,
    version: manifest.version,
    repoUrl: manifest.repository ?? lockEntry.url,
    description: manifest.description ?? '',
    engine: manifest.engine,
    commit: lockEntry.commit,
    compatible: classifyCompat(manifest.engine) === 'ok',
  };
  const metaRecord = meta as unknown as Record<string, unknown>;

  for (const p of manifest.plugins) {
    const lines = [
      `  // ${name}@${manifest.version} (${lockEntry.commit.slice(0, 7)})`,
      '  {',
      `    id: ${quote(p.id)},`,
      `    import: () => import(${quote(toImportSpecifier(name, p.entry))}),`,
      `    className: ${quote(p.className)},`,
      `    defaultConfig: ${inline(p.defaultConfig)},`,
    ];

    if (p.dependencies && p.dependencies.length > 0) {
      lines.push(`    dependencies: ${inline(p.dependencies)},`);
    }
    if (p.alwaysEnabled) {
      lines.push('    alwaysEnabled: true,');
    }
    if (hasLocales) {
      lines.push(`    locales: { en: () => import(${quote(`@plugins-external/${name}/${localesDir}/en.json`)}) },`);
    }
    lines.push("    source: 'external',", `    meta: ${expanded(metaRecord, 4)},`, '  },');

    descriptorBlocks.push(lines.join('\n'));

    if (!isCompatible(manifest.engine)) {
      report.incompatible.push({ id: p.id, engine: manifest.engine });
    }

    metaBlocks.push(`  ${key(p.id)}: ${expanded(metaRecord, 2)},`);
  }
}

/** Regenerate and write the committed generated manifest. Returns the sync report. */
export function writeGeneratedManifest(): SyncReport {
  const { source, report } = generateManifestSource();

  // Skip the write when nothing changed so a watching dev server is not poked.
  if (!isGeneratedManifestInSync(source)) {
    writeFileSync(GENERATED_MANIFEST_PATH, source, 'utf8');
  }

  return report;
}

/** True if the on-disk generated manifest already matches what sync would write. */
export function isGeneratedManifestInSync(source = generateManifestSource().source): boolean {
  const current = existsSync(GENERATED_MANIFEST_PATH) ? readFileSync(GENERATED_MANIFEST_PATH, 'utf8') : '';

  return current === source;
}
