import { FECType, Hertz, ModulationType, RfFrequency, RfSignal } from "../types";

const meteoSat9Signals: RfSignal[] = [
  {
    id: 'GEOS & R E-S',
    serverId: 1,
    noradId: 28912,
    frequency: 406.05e6 as RfFrequency,
    polarization: 'H',
    power: -110,
    bandwidth: 100e3 as Hertz,
    modulation: '8QAM' as ModulationType,
    fec: '3/4' as FECType,
    feed: 'https://eumetview.eumetsat.int/static-images/latestImages/EUMETSAT_MSGIODC_RGBNatColour_LowResolution.jpg',
    isImage: true,
    isExternal: true,
    isDegraded: false,
  },
  {
    id: 'GEOS & R S-E',
    serverId: 1,
    noradId: 28912,
    frequency: 1544.5e6 as RfFrequency,
    polarization: 'H',
    power: -110,
    bandwidth: 200e3 as Hertz,
    modulation: '8QAM' as ModulationType,
    fec: '3/4' as FECType,
    feed: 'https://eumetview.eumetsat.int/static-images/latestImages/EUMETSAT_MSGIODC_RGBNatColour_LowResolution.jpg',
    isImage: true,
    isExternal: true,
    isDegraded: false,
  },
  {
    id: 'TC & Ranging E-S',
    serverId: 1,
    noradId: 28912,
    frequency: 2067.731e6 as RfFrequency,
    polarization: 'H',
    power: -110,
    bandwidth: 1000e3 as Hertz,
    modulation: 'BPSK' as ModulationType,
    fec: '3/4' as FECType,
    feed: 'https://eumetview.eumetsat.int/static-images/latestImages/EUMETSAT_MSGIODC_RGBNatColour_LowResolution.jpg',
    isImage: true,
    isExternal: true,
    isDegraded: false,
  },
  {
    id: 'TM S-E',
    serverId: 1,
    noradId: 28912,
    frequency: 2245.5e6 as RfFrequency,
    polarization: 'V',
    power: -110,
    bandwidth: 1000e3 as Hertz,
    modulation: 'BPSK' as ModulationType,
    fec: '3/4' as FECType,
    feed: 'https://eumetview.eumetsat.int/static-images/latestImages/EUMETSAT_MSGIODC_RGBNatColour_LowResolution.jpg',
    isImage: true,
    isExternal: true,
    isDegraded: false,
  },
  {
    id: 'PGS S-E',
    serverId: 1,
    noradId: 28912,
    frequency: 1686.83e6 as RfFrequency,
    polarization: 'V',
    power: -110,
    bandwidth: 5400e3 as Hertz,
    modulation: 'QPSK' as ModulationType,
    fec: '3/4' as FECType,
    feed: 'https://eumetview.eumetsat.int/static-images/latestImages/EUMETSAT_MSGIODC_RGBNatColour_LowResolution.jpg',
    isImage: true,
    isExternal: true,
    isDegraded: false,
  },
  {
    id: 'HRIT E-S',
    serverId: 1,
    noradId: 28912,
    frequency: 2105.65e6 as RfFrequency,
    polarization: 'H',
    power: -110,
    bandwidth: 2000e3 as Hertz,
    modulation: 'QPSK' as ModulationType,
    fec: '3/4' as FECType,
    feed: 'https://eumetview.eumetsat.int/static-images/latestImages/EUMETSAT_MSGIODC_RGBNatColour_LowResolution.jpg',
    isImage: true,
    isExternal: true,
    isDegraded: false,
  },
  {
    id: 'HRIT S-E',
    serverId: 1,
    noradId: 28912,
    frequency: 1695.15e6 as RfFrequency,
    polarization: 'H',
    power: -110,
    bandwidth: 2000e3 as Hertz,
    modulation: 'QPSK' as ModulationType,
    fec: '3/4' as FECType,
    feed: 'https://eumetview.eumetsat.int/static-images/latestImages/EUMETSAT_MSGIODC_RGBNatColour_LowResolution.jpg',
    isImage: true,
    isExternal: true,
    isDegraded: false,
  },
  {
    id: 'LRIT E-S',
    serverId: 1,
    noradId: 28912,
    frequency: 2101.5e6 as RfFrequency,
    polarization: 'V',
    power: -110,
    bandwidth: 660e3 as Hertz,
    modulation: 'QPSK' as ModulationType,
    fec: '3/4' as FECType,
    feed: 'https://eumetview.eumetsat.int/static-images/latestImages/EUMETSAT_MSGIODC_RGBNatColour_LowResolution.jpg',
    isImage: true,
    isExternal: true,
    isDegraded: false,
  },
  {
    id: 'LRIT S-E',
    serverId: 1,
    noradId: 28912,
    frequency: 1691e6 as RfFrequency,
    polarization: 'V',
    power: -110,
    bandwidth: 660e3 as Hertz,
    modulation: 'QPSK' as ModulationType,
    fec: '3/4' as FECType,
    feed: 'https://eumetview.eumetsat.int/static-images/latestImages/EUMETSAT_MSGIODC_RGBNatColour_LowResolution.jpg',
    isImage: true,
    isExternal: true,
    isDegraded: false,
  },
  {
    id: 'DCS (international) E-S',
    serverId: 1,
    noradId: 28912,
    frequency: 402e6 as RfFrequency,
    polarization: 'H',
    power: -110,
    bandwidth: 3e3 as Hertz,
    modulation: 'BPSK' as ModulationType,
    fec: '3/4' as FECType,
    feed: 'https://eumetview.eumetsat.int/static-images/latestImages/EUMETSAT_MSGIODC_RGBNatColour_LowResolution.jpg',
    isImage: true,
    isExternal: true,
    isDegraded: false,
  },
  {
    id: 'DCS (regional) E-S',
    serverId: 1,
    noradId: 28912,
    frequency: 402.1e6 as RfFrequency,
    polarization: 'H',
    power: -110,
    bandwidth: 1.5e3 as Hertz,
    modulation: 'BPSK' as ModulationType,
    fec: '3/4' as FECType,
    feed: 'https://eumetview.eumetsat.int/static-images/latestImages/EUMETSAT_MSGIODC_RGBNatColour_LowResolution.jpg',
    isImage: true,
    isExternal: true,
    isDegraded: false,
  },
  {
    id: 'DCS S-E',
    serverId: 1,
    noradId: 28912,
    frequency: 1675.281e6 as RfFrequency,
    polarization: 'V',
    power: -110,
    bandwidth: 750e3 as Hertz,
    modulation: 'BPSK' as ModulationType,
    fec: '3/4' as FECType,
    feed: 'https://eumetview.eumetsat.int/static-images/latestImages/EUMETSAT_MSGIODC_RGBNatColour_LowResolution.jpg',
    isImage: true,
    isExternal: true,
    isDegraded: false,
  },
];

export const defaultSignalData: RfSignal[] = [
  ...meteoSat9Signals,
  {
    id: '1',
    serverId: 1,
    noradId: 1,
    frequency: 4810e6 as RfFrequency,
    polarization: 'H',
    power: -100,
    bandwidth: 10e6 as Hertz,
    modulation: '8QAM' as ModulationType,
    fec: '3/4' as FECType,
    feed: 'red-1.mp4',
    isDegraded: false,
  },
  {
    id: '2',
    serverId: 1,
    noradId: 1,
    frequency: 4798e6 as RfFrequency,
    polarization: 'H',
    power: -100,
    bandwidth: 10e6 as Hertz,
    modulation: '8QAM' as ModulationType,
    fec: '3/4' as FECType,
    feed: 'blue-1.mp4',
    isDegraded: false,
  },
  {
    id: '3',
    serverId: 1,
    noradId: 1,
    frequency: 4817e6 as RfFrequency,
    polarization: 'H',
    power: -100,
    bandwidth: 2e6 as Hertz,
    modulation: '8QAM' as ModulationType,
    fec: '3/4' as FECType,
    feed: 'blue-1.mp4',
    isDegraded: false,
  },
  {
    id: '4',
    serverId: 1,
    noradId: 1,
    frequency: 4826e6 as RfFrequency,
    polarization: 'H',
    power: -100,
    bandwidth: 1e6 as Hertz,
    modulation: '8QAM' as ModulationType,
    fec: '3/4' as FECType,
    feed: 'blue-1.mp4',
    isDegraded: false,
  },
  {
    id: '5',
    serverId: 1,
    noradId: 1,
    frequency: 4785e6 as RfFrequency,
    polarization: 'H',
    power: -100,
    bandwidth: 4e6 as Hertz,
    modulation: '8QAM' as ModulationType,
    fec: '3/4' as FECType,
    feed: 'blue-1.mp4',
    isDegraded: false,
  },
  {
    id: '6',
    serverId: 1,
    noradId: 1,
    frequency: 4833e6 as RfFrequency,
    polarization: 'H',
    power: -100,
    bandwidth: 10e6 as Hertz,
    modulation: 'BPSK' as ModulationType,
    fec: '1/4' as FECType,
    feed: 'blue-1.mp4',
    isDegraded: false
  },
];
