/**
 * AUTO-GENERATED by `pnpm run plugin -- sync`. DO NOT EDIT BY HAND.
 *
 * Regenerated from external-plugins.json + the signal-range-plugin.json of each
 * clone under src/plugins-external/. Committed so a fresh checkout typechecks
 * and builds without running any tool; empty upstream when no external plugins
 * are installed.
 *
 * - `externalPluginManifest` is spread onto the end of `pluginManifest`, giving
 *   each external plugin its own async chunk exactly like a built-in.
 * - `externalPluginMeta` is read by the dev menu so it can list installed
 *   external plugins (version, repo, compat) without fetching anything at
 *   runtime. `compatible` is precomputed at sync time against the host
 *   package.json version.
 */
import type { ExternalPluginMetaEntry, PluginDescriptor } from './plugin-descriptor';

export const externalPluginManifest: PluginDescriptor[] = [];

export const externalPluginMeta: Record<string, ExternalPluginMetaEntry> = {};
